### ISSUE TITLE
Fix the diagram

### ISSUE THREAD

**Issue by xposix** [giusedroid/aws-serverless-monitoring#10]
There would be a couple of things to change:
* Internet Gateway is only for outbound traffic
* Add NAT Gateways
* Add ALB 
* AutoScaling Groups are just for EC2, need to change to whatever it is

**Comment by giusedroid** [comment]
Hi @xposix 

Many thanks for opening this issue.

Some observations
- the IGW is needed so that I can deploy an internet-facing ALB in a public subnet. I also think an IGW is needed for inbound traffic too. Please have a look at [this](https://aws.amazon.com/it/premiumsupport/knowledge-center/public-load-balancer-private-ec2/) and [this](https://docs.aws.amazon.com/en_us/vpc/latest/userguide/VPC_Internet_Gateway.html). Furthermore, an IGW is needed to allow traffic through the NAT. Do you mean I should get rid of the IGW in the diagram, so that it looks cleaner?
- Will add the NAT Gateways, thanks for pointing that out.
- What do you mean with add the ALBs? Did I use the wrong symbol for an ALB? I think I've added the ALB in both the public subnets. Can you please double check that?
- s/Auto Scaling Group/AWS::ApplicationAutoScaling::ScalableTarget

**Comment by giusedroid** [comment]
Merged in!
